GET http://localhost:5000/api/v1/books
Accept: application/json



###
GET http://localhost:5000/api/v1/books/{id}

###
PUT http://localhost:5000/api/v1/books/add
Content-Type: application/json

{

     "name":"",
     "author":"",
     "genre":"",
     "dateOfRelease":"",
     "bookImage":"",
     "rating":"",
     "price":"",
}

###
PUT http://localhost:5000/api/v1/books/update/{id}
Content-Type: application/json

{

     "name":"",
     "author":"",
     "genre":"",
     "dateOfRelease":"",
     "bookImage":"",
     "rating":"",
     "price":"",
}

###
DELETE http://localhost:5000/api/v1/books/{id}